Safety Module Activation
moonwell-fi/moonwell-contracts-v2 pull request #166
Opened 2024-03-31 04:39 UTC by ElliotFriedman

Draft

Awaiting reward speed numbers.

2024-03-31 14:03 UTC, anajuliabit requested changes

2024-03-31 14:03 UTC, anajuliabit commented on src/proposals/mips/mip-b16/mip-b16.sol
> +        );
```suggestion
        /// safety check to ensure no moobeam actions are run
        require(
            baseActions.length == 1,
            "MIP-M26: should have base actions"
        );
```

2024-04-01 23:40 UTC, anajuliabit commented
```
Governor multichain proposal calldata
  0x7d5e81e2000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000003c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000bebdb6c8ddc678ffa9f8748f85c815c556dd8ac600000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000244b19a437e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000001c00000000000000000000000008b621804a7637b781e2bbd58e256a591f2df7d51000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc1700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000044398340250000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc1700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000729417574686f72733a20456c6c696f742c20416e610a0a2a2a53756d6d6172792a2a3a2041637469766174652072657761726420656d697373696f6e7320666f722057454c4c206f6e20426173650a0a2a2a4f766572766965772a2a0a0a54686520636f6d6d756e6974792068617320726563656e746c7920766f74656420746f20696d706c656d656e7420746865206e6577204d756c7469636861696e20476f7665726e6f720a636f6e747261637420746f20676f7665726e20746865204d6f6f6e77656c6c2050726f746f636f6c2e204164646974696f6e616c6c792c2061206e6577206d756c7469636861696e2057454c4c0a746f6b656e207574696c697a696e67207468652078455243323020746f6b656e207374616e6461726420686173206265656e20726174696669656420666f72207573616765206f6e20426173652c0a77686963682069732061207369676e69666963616e74206d696c6573746f6e6520666f722074686520636f6d6d756e6974792e2042792061646f7074696e672074686973206e657720426173650a6e61746976652057454c4c20746f6b656e2c20746f6b656e686f6c646572732063616e206e6f77207374616b6520746865697220746f6b656e73206469726563746c79206f6e204261736520616e640a706172746963697061746520696e206f6e636861696e20676f7665726e616e636520766f74696e672e2054686520536166657479204d6f64756c6520776173206465706c6f796564206f6e20426173650a616e64206973207265676973746572656420696e20746865204d756c7469636861696e20566f746520436f6c6c656374696f6e20636f6e7472616374206173206120736f75726365206f660a766f74696e6720706f7765722c20616c6c6f77696e67207573657273207365637572696e67207468652070726f746f636f6c20746f20706172746963697061746520696e20676f7665726e616e63652e0a0a496e697469616c6c792c207265776172647320776572652073657420746f2030206f6e20746865206e657720536166657479204d6f64756c65206f6e20426173652e20546869732070726f706f73616c0a61696d7320746f20656e61626c65207265776172647320666f7220757365727320696e2074686520536166657479204d6f64756c65207769746820746865206e65772042617365206e61746976650a57454c4c20746f6b656e2e0a0a4265666f7265207468697320636f6e66696775726174696f6e2069732061626c6520746f206f636375722c20616d706c652074696d652073686f756c6420626520676976656e20746f207468650a636f6d6d756e69747920746f2062726964676520746865697220576f726d686f6c6520777261707065642057454c4c2066726f6d20426173652c20746f204d6f6f6e6265616d20616e64206261636b0a696e207468652042617365206e617469766520666f726d2e20496e697469616c20657374696d61746573206f662074686973206d6967726174696f6e2074696d6520617265206174206d696e696d756d0a36206461797320696620616c6c20576f726d686f6c6520577261707065642057454c4c2077617320636f6e7374616e746c7920627269646765642066726f6d2042617365206261636b20746f0a4d6f6f6e6265616d20616e6420576f726d686f6c6520646964206e6f742064656c6179207472616e73666572732e0a0a496d706c656d656e746174696f6e3a20412070726f706f73616c2077696c6c206265206372656174656420627920536f6c6964697479204c6162732074686174207365747320616e642066756e64730a7265776172647320746861742077696c6c20626520676976656e20746f20616c6c20536166657479204d6f64756c65205374616b6572732e2057617264656e2046696e616e63652077696c6c0a70726f76696465207265636f6d6d656e646174696f6e73206f6e20696e697469616c20726577617264207370656564732e0a0a436f6e636c7573696f6e3a20416464696e67207265776172647320746f2074686520536166657479204d6f64756c65206f6e2042617365206372656174657320696e63656e746976657320666f720a757365727320746f206261636b73746f70207468652070726f746f636f6c207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e205374616b696e672057454c4c0a696e2074686520536166657479204d6f64756c65206e6f74206f6e6c7920676976657320636f6d6d756e697479206d656d6265727320746865206162696c69747920746f206561726e206e61746976650a7969656c64206f6e20746865697220686f6c64696e67732c2062757420616c736f2070726573656e747320616e20656173792077617920746f2067657420696e766f6c76656420696e0a676f7665726e616e63652061732057454c4c206973206175746f6d61746963616c6c792073656c662064656c6567617465642e0a0000000000000000000000000000000000000000000000
```

2024-04-01 23:45 UTC, anajuliabit commented
```
Governor multichain proposal calldata
  0x7d5e81e2000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000bebdb6c8ddc678ffa9f8748f85c815c556dd8ac600000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000344b19a437e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000002c00000000000000000000000008b621804a7637b781e2bbd58e256a591f2df7d51000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a88594d404727625a9437c3f886c7643872296ae000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc170000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000006423b872dd00000000000000000000000074cbb1e8b68ddd13b28684eca202a351afd45eaa00000000000000000000000065a633e8e379f9358c389c75ff1d913a92ab95b800000000000000000000000000000000000000000002a05345946e39fdfd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044398340250000000000000000000000000000000000000000000000000c7035d444b7c1e8000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc17000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007be23204d49502d423136204261736520536166657479204d6f64756c652041637469766174696f6e0a0a2a2a417574686f72732a2a3a20456c6c696f742c20416e610a0a2a2a53756d6d6172792a2a0a0a546869732070726f706f73616c2061696d7320746f2061637469766174652072657761726420656d697373696f6e7320666f7220746865206e657720536166657479204d6f64756c65206f6e0a426173652c20696e63656e746976697a696e6720757365727320746f2068656c702073656375726520746865204d6f6f6e77656c6c2070726f746f636f6c207468726f756768207374616b696e670a616e6420706172746963697061746520696e206f6e636861696e20676f7665726e616e63652e0a0a2a2a4f766572766965772a2a0a0a546865204d6f6f6e77656c6c20636f6d6d756e6974792068617320726563656e746c7920617070726f7665642074686520696d706c656d656e746174696f6e206f662061206e65770a6d756c7469636861696e20676f7665726e6f7220636f6e747261637420746f20676f7665726e20746865204d6f6f6e77656c6c2070726f746f636f6c2e204164646974696f6e616c6c792c20610a6e65772042617365206e61746976652057454c4c20746f6b656e207574696c697a696e67207468652078455243323020746f6b656e207374616e6461726420686173206265656e20617070726f7665640a666f722075736167652c2077686963682069732061207369676e69666963616e74206d696c6573746f6e6520666f722074686520636f6d6d756e6974792e2042792061646f7074696e6720746869730a6e65772042617365206e61746976652057454c4c20746f6b656e2c20746f6b656e686f6c646572732077696c6c20736f6f6e2062652061626c6520746f207374616b652074686569722057454c4c0a6469726563746c79206f6e204261736520616e6420766f746520696e206f6e636861696e20676f7665726e616e63652e2041206e657720536166657479204d6f64756c652068617320616c72656164790a6265656e206465706c6f796564206f6e204261736520616e64206973207265676973746572656420696e20746865204d756c7469636861696e20566f746520436f6c6c656374696f6e0a636f6e7472616374206173206120736f75726365206f6620766f74696e6720706f7765722c20616c6c6f77696e67207573657273207365637572696e67207468652070726f746f636f6c20746f0a706172746963697061746520696e20676f7665726e616e63652e20496e697469616c6c792c207265776172647320776572652073657420746f2030206f6e20746865206e6577205361666574790a4d6f64756c65206f6e20426173652e20546869732070726f706f73616c2061696d7320746f20656e61626c65207265776172647320666f7220757365727320696e20746865205361666574790a4d6f64756c65207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e0a0a2a2a496d706c656d656e746174696f6e2a2a0a0a546869732070726f706f73616c2077696c6c2073657420616e642066756e64207265776172647320746861742077696c6c20626520646973747269627574656420746f20616c6c205361666574790a4d6f64756c65207374616b657273206f6e20426173652e20496e697469616c20726577617264207370656564732077696c6c2062652073657420746f207468652076616c75650a7265636f6d6d656e64656420627920656d697373696f6e732061646d696e2057617264656e2046696e616e6365206f6620302e383936323735353131363438393631303030302057454c4c207065720a7365636f6e642e202a2a566f74696e672a2a0a0a4120225961792220766f746520696e6469636174657320796f757220737570706f727420666f7220656e61626c696e672072657761726420656d697373696f6e7320666f7220746865205361666574790a4d6f64756c65206f6e20426173652c206173206f75746c696e656420696e20746869732070726f706f73616c2e204120224e61792220766f746520696e6469636174657320796f75720a6f70706f736974696f6e20746f20656e61626c696e672072657761726420656d697373696f6e7320666f722074686520536166657479204d6f64756c65206f6e20426173652e0a0a2a2a436f6e636c7573696f6e2a2a0a0a416464696e67207265776172647320746f2074686520536166657479204d6f64756c65206f6e2042617365206372656174657320696e63656e746976657320666f7220757365727320746f0a6261636b73746f70207468652070726f746f636f6c207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e205374616b696e672057454c4c20696e207468650a536166657479204d6f64756c65206e6f74206f6e6c7920676976657320636f6d6d756e697479206d656d6265727320746865206162696c69747920746f206561726e206e6174697665207969656c640a6f6e20746865697220686f6c64696e67732c2062757420616c736f2070726573656e747320616e20656173792077617920746f2067657420696e766f6c76656420696e20676f7665726e616e63650a61732057454c4c206973206175746f6d61746963616c6c792073656c662064656c6567617465642e0a0000
```

2024-04-01 23:49 UTC, anajuliabit commented
```
Governor multichain proposal calldata
  0x7d5e81e2000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000bebdb6c8ddc678ffa9f8748f85c815c556dd8ac600000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000344b19a437e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000002c00000000000000000000000008b621804a7637b781e2bbd58e256a591f2df7d51000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a88594d404727625a9437c3f886c7643872296ae000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc170000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000006423b872dd00000000000000000000000074cbb1e8b68ddd13b28684eca202a351afd45eaa00000000000000000000000065a633e8e379f9358c389c75ff1d913a92ab95b800000000000000000000000000000000000000000002a05345946e39fdfd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044398340250000000000000000000000000000000000000000000000000c7035d444b7c1e8000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc17000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007be23204d49502d423136204261736520536166657479204d6f64756c652041637469766174696f6e0a0a2a2a417574686f72732a2a3a20456c6c696f742c20416e610a0a2a2a53756d6d6172792a2a0a0a546869732070726f706f73616c2061696d7320746f2061637469766174652072657761726420656d697373696f6e7320666f7220746865206e657720536166657479204d6f64756c65206f6e0a426173652c20696e63656e746976697a696e6720757365727320746f2068656c702073656375726520746865204d6f6f6e77656c6c2070726f746f636f6c207468726f756768207374616b696e670a616e6420706172746963697061746520696e206f6e636861696e20676f7665726e616e63652e0a0a2a2a4f766572766965772a2a0a0a546865204d6f6f6e77656c6c20636f6d6d756e6974792068617320726563656e746c7920617070726f7665642074686520696d706c656d656e746174696f6e206f662061206e65770a6d756c7469636861696e20676f7665726e6f7220636f6e747261637420746f20676f7665726e20746865204d6f6f6e77656c6c2070726f746f636f6c2e204164646974696f6e616c6c792c20610a6e65772042617365206e61746976652057454c4c20746f6b656e207574696c697a696e67207468652078455243323020746f6b656e207374616e6461726420686173206265656e20617070726f7665640a666f722075736167652c2077686963682069732061207369676e69666963616e74206d696c6573746f6e6520666f722074686520636f6d6d756e6974792e2042792061646f7074696e6720746869730a6e65772042617365206e61746976652057454c4c20746f6b656e2c20746f6b656e686f6c646572732077696c6c20736f6f6e2062652061626c6520746f207374616b652074686569722057454c4c0a6469726563746c79206f6e204261736520616e6420766f746520696e206f6e636861696e20676f7665726e616e63652e2041206e657720536166657479204d6f64756c652068617320616c72656164790a6265656e206465706c6f796564206f6e204261736520616e64206973207265676973746572656420696e20746865204d756c7469636861696e20566f746520436f6c6c656374696f6e0a636f6e7472616374206173206120736f75726365206f6620766f74696e6720706f7765722c20616c6c6f77696e67207573657273207365637572696e67207468652070726f746f636f6c20746f0a706172746963697061746520696e20676f7665726e616e63652e20496e697469616c6c792c207265776172647320776572652073657420746f2030206f6e20746865206e6577205361666574790a4d6f64756c65206f6e20426173652e20546869732070726f706f73616c2061696d7320746f20656e61626c65207265776172647320666f7220757365727320696e20746865205361666574790a4d6f64756c65207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e0a0a2a2a496d706c656d656e746174696f6e2a2a0a0a546869732070726f706f73616c2077696c6c2073657420616e642066756e64207265776172647320746861742077696c6c20626520646973747269627574656420746f20616c6c205361666574790a4d6f64756c65207374616b657273206f6e20426173652e20496e697469616c20726577617264207370656564732077696c6c2062652073657420746f207468652076616c75650a7265636f6d6d656e64656420627920656d697373696f6e732061646d696e2057617264656e2046696e616e6365206f6620302e383936323735353131363438393631303030302057454c4c207065720a7365636f6e642e202a2a566f74696e672a2a0a0a4120225961792220766f746520696e6469636174657320796f757220737570706f727420666f7220656e61626c696e672072657761726420656d697373696f6e7320666f7220746865205361666574790a4d6f64756c65206f6e20426173652c206173206f75746c696e656420696e20746869732070726f706f73616c2e204120224e61792220766f746520696e6469636174657320796f75720a6f70706f736974696f6e20746f20656e61626c696e672072657761726420656d697373696f6e7320666f722074686520536166657479204d6f64756c65206f6e20426173652e0a0a2a2a436f6e636c7573696f6e2a2a0a0a416464696e67207265776172647320746f2074686520536166657479204d6f64756c65206f6e2042617365206372656174657320696e63656e746976657320666f7220757365727320746f0a6261636b73746f70207468652070726f746f636f6c207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e205374616b696e672057454c4c20696e207468650a536166657479204d6f64756c65206e6f74206f6e6c7920676976657320636f6d6d756e697479206d656d6265727320746865206162696c69747920746f206561726e206e6174697665207969656c640a6f6e20746865697220686f6c64696e67732c2062757420616c736f2070726573656e747320616e20656173792077617920746f2067657420696e766f6c76656420696e20676f7665726e616e63650a61732057454c4c206973206175746f6d61746963616c6c792073656c662064656c6567617465642e0a0000
```

2024-04-02 00:01 UTC, anajuliabit commented
```
  Governor multichain proposal calldata
  0x7d5e81e2000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000bebdb6c8ddc678ffa9f8748f85c815c556dd8ac600000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000344b19a437e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000002c00000000000000000000000008b621804a7637b781e2bbd58e256a591f2df7d51000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a88594d404727625a9437c3f886c7643872296ae000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc170000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000006423b872dd00000000000000000000000074cbb1e8b68ddd13b28684eca202a351afd45eaa00000000000000000000000065a633e8e379f9358c389c75ff1d913a92ab95b800000000000000000000000000000000000000000002a05345946e39fdfd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044398340250000000000000000000000000000000000000000000000000c7035d444b7c1e8000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc17000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007be23204d49502d423136204261736520536166657479204d6f64756c652041637469766174696f6e0a0a2a2a417574686f72732a2a3a20456c6c696f742c20416e610a0a2a2a53756d6d6172792a2a0a0a546869732070726f706f73616c2061696d7320746f2061637469766174652072657761726420656d697373696f6e7320666f7220746865206e657720536166657479204d6f64756c65206f6e0a426173652c20696e63656e746976697a696e6720757365727320746f2068656c702073656375726520746865204d6f6f6e77656c6c2070726f746f636f6c207468726f756768207374616b696e670a616e6420706172746963697061746520696e206f6e636861696e20676f7665726e616e63652e0a0a2a2a4f766572766965772a2a0a0a546865204d6f6f6e77656c6c20636f6d6d756e6974792068617320726563656e746c7920617070726f7665642074686520696d706c656d656e746174696f6e206f662061206e65770a6d756c7469636861696e20676f7665726e6f7220636f6e747261637420746f20676f7665726e20746865204d6f6f6e77656c6c2070726f746f636f6c2e204164646974696f6e616c6c792c20610a6e65772042617365206e61746976652057454c4c20746f6b656e207574696c697a696e67207468652078455243323020746f6b656e207374616e6461726420686173206265656e20617070726f7665640a666f722075736167652c2077686963682069732061207369676e69666963616e74206d696c6573746f6e6520666f722074686520636f6d6d756e6974792e2042792061646f7074696e6720746869730a6e65772042617365206e61746976652057454c4c20746f6b656e2c20746f6b656e686f6c646572732077696c6c20736f6f6e2062652061626c6520746f207374616b652074686569722057454c4c0a6469726563746c79206f6e204261736520616e6420766f746520696e206f6e636861696e20676f7665726e616e63652e2041206e657720536166657479204d6f64756c652068617320616c72656164790a6265656e206465706c6f796564206f6e204261736520616e64206973207265676973746572656420696e20746865204d756c7469636861696e20566f746520436f6c6c656374696f6e0a636f6e7472616374206173206120736f75726365206f6620766f74696e6720706f7765722c20616c6c6f77696e67207573657273207365637572696e67207468652070726f746f636f6c20746f0a706172746963697061746520696e20676f7665726e616e63652e20496e697469616c6c792c207265776172647320776572652073657420746f2030206f6e20746865206e6577205361666574790a4d6f64756c65206f6e20426173652e20546869732070726f706f73616c2061696d7320746f20656e61626c65207265776172647320666f7220757365727320696e20746865205361666574790a4d6f64756c65207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e0a0a2a2a496d706c656d656e746174696f6e2a2a0a0a546869732070726f706f73616c2077696c6c2073657420616e642066756e64207265776172647320746861742077696c6c20626520646973747269627574656420746f20616c6c205361666574790a4d6f64756c65207374616b657273206f6e20426173652e20496e697469616c20726577617264207370656564732077696c6c2062652073657420746f207468652076616c75650a7265636f6d6d656e64656420627920656d697373696f6e732061646d696e2057617264656e2046696e616e6365206f6620302e383936323735353131363438393631303030302057454c4c207065720a7365636f6e642e202a2a566f74696e672a2a0a0a4120225961792220766f746520696e6469636174657320796f757220737570706f727420666f7220656e61626c696e672072657761726420656d697373696f6e7320666f7220746865205361666574790a4d6f64756c65206f6e20426173652c206173206f75746c696e656420696e20746869732070726f706f73616c2e204120224e61792220766f746520696e6469636174657320796f75720a6f70706f736974696f6e20746f20656e61626c696e672072657761726420656d697373696f6e7320666f722074686520536166657479204d6f64756c65206f6e20426173652e0a0a2a2a436f6e636c7573696f6e2a2a0a0a416464696e67207265776172647320746f2074686520536166657479204d6f64756c65206f6e2042617365206372656174657320696e63656e746976657320666f7220757365727320746f0a6261636b73746f70207468652070726f746f636f6c207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e205374616b696e672057454c4c20696e207468650a536166657479204d6f64756c65206e6f74206f6e6c7920676976657320636f6d6d756e697479206d656d6265727320746865206162696c69747920746f206561726e206e6174697665207969656c640a6f6e20746865697220686f6c64696e67732c2062757420616c736f2070726573656e747320616e20656173792077617920746f2067657420696e766f6c76656420696e20676f7665726e616e63650a61732057454c4c206973206175746f6d61746963616c6c792073656c662064656c6567617465642e0a0000
  

Proposal Description:

# MIP-B16 Base Safety Module Activation

**Authors**: Elliot, Ana

**Summary**

This proposal aims to activate reward emissions for the new Safety Module on
Base, incentivizing users to help secure the Moonwell protocol through staking
and participate in onchain governance.

**Overview**

The Moonwell community has recently approved the implementation of a new
multichain governor contract to govern the Moonwell protocol. Additionally, a
new Base native WELL token utilizing the xERC20 token standard has been approved
for usage, which is a significant milestone for the community. By adopting this
new Base native WELL token, tokenholders will soon be able to stake their WELL
directly on Base and vote in onchain governance. A new Safety Module has already
been deployed on Base and is registered in the Multichain Vote Collection
contract as a source of voting power, allowing users securing the protocol to
participate in governance. Initially, rewards were set to 0 on the new Safety
Module on Base. This proposal aims to enable rewards for users in the Safety
Module with the new Base native WELL token.

**Implementation**

This proposal will set and fund rewards that will be distributed to all Safety
Module stakers on Base. Initial reward speeds will be set to the value
recommended by emissions admin Warden Finance of 0.8962755116489610000 WELL per
second. **Voting**

A "Yay" vote indicates your support for enabling reward emissions fo [...]

2024-04-02 00:02 UTC, anajuliabit submitted a review, later dismissed

2024-04-02 00:04 UTC, lyoungblood commented
I got:
```
Governor multichain proposal calldata
  0x7d5e81e2000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000bebdb6c8ddc678ffa9f8748f85c815c556dd8ac600000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000344b19a437e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000002c00000000000000000000000008b621804a7637b781e2bbd58e256a591f2df7d51000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a88594d404727625a9437c3f886c7643872296ae000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc170000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000006423b872dd00000000000000000000000074cbb1e8b68ddd13b28684eca202a351afd45eaa00000000000000000000000065a633e8e379f9358c389c75ff1d913a92ab95b800000000000000000000000000000000000000000002a05345946e39fdfd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044398340250000000000000000000000000000000000000000000000000c7035d444b7c1e8000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc17000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007be23204d49502d423136204261736520536166657479204d6f64756c652041637469766174696f6e0a0a2a2a417574686f72732a2a3a20456c6c696f742c20416e610a0a2a2a53756d6d6172792a2a0a0a546869732070726f706f73616c2061696d7320746f2061637469766174652072657761726420656d697373696f6e7320666f7220746865206e657720536166657479204d6f64756c65206f6e0a426173652c20696e63656e746976697a696e6720757365727320746f2068656c702073656375726520746865204d6f6f6e77656c6c2070726f746f636f6c207468726f756768207374616b696e670a616e6420706172746963697061746520696e206f6e636861696e20676f7665726e616e63652e0a0a2a2a4f766572766965772a2a0a0a546865204d6f6f6e77656c6c20636f6d6d756e6974792068617320726563656e746c7920617070726f7665642074686520696d706c656d656e746174696f6e206f662061206e65770a6d756c7469636861696e20676f7665726e6f7220636f6e747261637420746f20676f7665726e20746865204d6f6f6e77656c6c2070726f746f636f6c2e204164646974696f6e616c6c792c20610a6e65772042617365206e61746976652057454c4c20746f6b656e207574696c697a696e67207468652078455243323020746f6b656e207374616e6461726420686173206265656e20617070726f7665640a666f722075736167652c2077686963682069732061207369676e69666963616e74206d696c6573746f6e6520666f722074686520636f6d6d756e6974792e2042792061646f7074696e6720746869730a6e65772042617365206e61746976652057454c4c20746f6b656e2c20746f6b656e686f6c646572732077696c6c20736f6f6e2062652061626c6520746f207374616b652074686569722057454c4c0a6469726563746c79206f6e204261736520616e6420766f746520696e206f6e636861696e20676f7665726e616e63652e2041206e657720536166657479204d6f64756c652068617320616c72656164790a6265656e206465706c6f796564206f6e204261736520616e64206973207265676973746572656420696e20746865204d756c7469636861696e20566f746520436f6c6c656374696f6e0a636f6e7472616374206173206120736f75726365206f6620766f74696e6720706f7765722c20616c6c6f77696e67207573657273207365637572696e67207468652070726f746f636f6c20746f0a706172746963697061746520696e20676f7665726e616e63652e20496e697469616c6c792c207265776172647320776572652073657420746f2030206f6e20746865206e6577205361666574790a4d6f64756c65206f6e20426173652e20546869732070726f706f73616c2061696d7320746f20656e61626c65207265776172647320666f7220757365727320696e20746865205361666574790a4d6f64756c65207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e0a0a2a2a496d706c656d656e746174696f6e2a2a0a0a546869732070726f706f73616c2077696c6c2073657420616e642066756e64207265776172647320746861742077696c6c20626520646973747269627574656420746f20616c6c205361666574790a4d6f64756c65207374616b657273206f6e20426173652e20496e697469616c20726577617264207370656564732077696c6c2062652073657420746f207468652076616c75650a7265636f6d6d656e64656420627920656d697373696f6e732061646d696e2057617264656e2046696e616e6365206f6620302e383936323735353131363438393631303030302057454c4c207065720a7365636f6e642e202a2a566f74696e672a2a0a0a4120225961792220766f746520696e6469636174657320796f757220737570706f727420666f7220656e61626c696e672072657761726420656d697373696f6e7320666f7220746865205361666574790a4d6f64756c65206f6e20426173652c206173206f75746c696e656420696e20746869732070726f706f73616c2e204120224e61792220766f746520696e6469636174657320796f75720a6f70706f736974696f6e20746f20656e61626c696e672072657761726420656d697373696f6e7320666f722074686520536166657479204d6f64756c65206f6e20426173652e0a0a2a2a436f6e636c7573696f6e2a2a0a0a416464696e67207265776172647320746f2074686520536166657479204d6f64756c65206f6e2042617365206372656174657320696e63656e746976657320666f7220757365727320746f0a6261636b73746f70207468652070726f746f636f6c207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e205374616b696e672057454c4c20696e207468650a536166657479204d6f64756c65206e6f74206f6e6c7920676976657320636f6d6d756e697479206d656d6265727320746865206162696c69747920746f206561726e206e6174697665207969656c640a6f6e20746865697220686f6c64696e67732c2062757420616c736f2070726573656e747320616e20656173792077617920746f2067657420696e766f6c76656420696e20676f7665726e616e63650a61732057454c4c206973206175746f6d61746963616c6c792073656c662064656c6567617465642e0a0000
```

2024-04-06 20:53 UTC, lyoungblood commented
My generated calldata matches:
```
0x7d5e81e2000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000c8e2b0cd52cf01b0ce87d389daa3d414d4ce29f300000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000344b19a437e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000002c00000000000000000000000008b621804a7637b781e2bbd58e256a591f2df7d51000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a88594d404727625a9437c3f886c7643872296ae000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc170000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000006423b872dd00000000000000000000000074cbb1e8b68ddd13b28684eca202a351afd45eaa00000000000000000000000065a633e8e379f9358c389c75ff1d913a92ab95b8000000000000000000000000000000000000000000024e55a3c8a1ba0f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044398340250000000000000000000000000000000000000000000000000c7035d444b7c1e8000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc17000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ef23204d49502d423136204261736520536166657479204d6f64756c652041637469766174696f6e2052657375626d697373696f6e0a0a2a2a417574686f72732a2a3a20456c6c696f742c20416e610a0a23232053696d706c652053756d6d6172790a0a546865206f726967696e616c2070726f706f73616c2077617320617070726f7665642062757420636f6e7461696e656420616e206572726f7220746861742070726576656e7465640a7375636365737366756c20657865637574696f6e206f6e204d6f6f6e6265616d2e205468697320697373756520686173206265656e20636f7272656374656420696e20746869730a72657375626d697373696f6e2e20496620746869732070726f706f73616c207061737365732c2074686520636f6d6d756e6974792063616e2065787065637420746f206861766520726577617264730a656e61626c656420666f722074686520536166657479204d6f64756c65206f6e2042617365206f6e2054687572736461792e0a0a23232053756d6d6172790a0a546869732070726f706f73616c2061696d7320746f2061637469766174652072657761726420656d697373696f6e7320666f7220746865206e657720536166657479204d6f64756c65206f6e0a426173652c20696e63656e746976697a696e6720757365727320746f2068656c702073656375726520746865204d6f6f6e77656c6c2070726f746f636f6c207468726f756768207374616b696e670a616e6420706172746963697061746520696e206f6e636861696e20676f7665726e616e63652e0a0a2323204f766572766965770a0a546865204d6f6f6e77656c6c20636f6d6d756e6974792068617320726563656e746c7920617070726f7665642074686520696d706c656d656e746174696f6e206f662061206e65770a6d756c7469636861696e20676f7665726e6f7220636f6e747261637420746f20676f7665726e20746865204d6f6f6e77656c6c2070726f746f636f6c2e204164646974696f6e616c6c792c20610a6e65772042617365206e61746976652057454c4c20746f6b656e207574696c697a696e67207468652078455243323020746f6b656e207374616e6461726420686173206265656e20617070726f7665640a666f722075736167652c2077686963682069732061207369676e69666963616e74206d696c6573746f6e6520666f722074686520636f6d6d756e6974792e2042792061646f7074696e6720746869730a6e65772042617365206e61746976652057454c4c20746f6b656e2c20746f6b656e686f6c646572732077696c6c20736f6f6e2062652061626c6520746f207374616b652074686569722057454c4c0a6469726563746c79206f6e204261736520616e6420766f746520696e206f6e636861696e20676f7665726e616e63652e2041206e657720536166657479204d6f64756c652068617320616c72656164790a6265656e206465706c6f796564206f6e204261736520616e64206973207265676973746572656420696e20746865204d756c7469636861696e20566f746520436f6c6c656374696f6e0a636f6e7472616374206173206120736f75726365206f6620766f74696e6720706f7765722c20616c6c6f77696e67207573657273207365637572696e67207468652070726f746f636f6c20746f0a706172746963697061746520696e20676f7665726e616e63652e20496e697469616c6c792c207265776172647320776572652073657420746f2030206f6e20746865206e6577205361666574790a4d6f64756c65206f6e20426173652e20546869732070726f706f73616c2061696d7320746f20656e61626c65207265776172647320666f7220757365727320696e20746865205361666574790a4d6f64756c65207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e0a0a232320496d706c656d656e746174696f6e0a0a546869732070726f706f73616c2077696c6c2073657420616e642066756e64207265776172647320746861742077696c6c20626520646973747269627574656420746f20616c6c205361666574790a4d6f64756c65207374616b657273206f6e20426173652e20496e697469616c20726577617264207370656564732077696c6c2062652073657420746f207468652076616c75650a7265636f6d6d656e64656420627920656d697373696f6e732061646d696e2057617264656e2046696e616e6365206f6620302e383936323735353131363438393631303030302057454c4c207065720a7365636f6e642e202a2a566f74696e672a2a0a0a4120225961792220766f746520696e6469636174657320796f757220737570706f727420666f7220656e61626c696e672072657761726420656d697373696f6e7320666f7220746865205361666574790a4d6f64756c65206f6e20426173652c206173206f75746c696e656420696e20746869732070726f706f73616c2e204120224e61792220766f746520696e6469636174657320796f75720a6f70706f736974696f6e20746f20656e61626c696e672072657761726420656d697373696f6e7320666f722074686520536166657479204d6f64756c65206f6e20426173652e0a0a232320436f6e636c7573696f6e0a0a416464696e67207265776172647320746f2074686520536166657479204d6f64756c65206f6e2042617365206372656174657320696e63656e746976657320666f7220757365727320746f0a6261636b73746f70207468652070726f746f636f6c207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e205374616b696e672057454c4c20696e207468650a536166657479204d6f64756c65206e6f74206f6e6c7920676976657320636f6d6d756e697479206d656d6265727320746865206162696c69747920746f206561726e206e6174697665207969656c640a6f6e20746865697220686f6c64696e67732c2062757420616c736f2070726573656e747320616e20656173792077617920746f2067657420696e766f6c76656420696e20676f7665726e616e63650a61732057454c4c206973206175746f6d61746963616c6c792073656c662064656c6567617465642e0a0000000000000000000000000000000000
```

2024-04-06 21:04 UTC, anajuliabit commented
```
  Governor multichain proposal calldata
  0x7d5e81e2000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004c00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000c8e2b0cd52cf01b0ce87d389daa3d414d4ce29f300000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000344b19a437e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000002c00000000000000000000000008b621804a7637b781e2bbd58e256a591f2df7d51000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000a88594d404727625a9437c3f886c7643872296ae000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc170000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000006423b872dd00000000000000000000000074cbb1e8b68ddd13b28684eca202a351afd45eaa00000000000000000000000065a633e8e379f9358c389c75ff1d913a92ab95b8000000000000000000000000000000000000000000024e55a3c8a1ba0f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044398340250000000000000000000000000000000000000000000000000c7035d444b7c1e8000000000000000000000000e66e3a37c3274ac24fe8590f7d84a2427194dc17000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ef23204d49502d423136204261736520536166657479204d6f64756c652041637469766174696f6e2052657375626d697373696f6e0a0a2a2a417574686f72732a2a3a20456c6c696f742c20416e610a0a23232053696d706c652053756d6d6172790a0a546865206f726967696e616c2070726f706f73616c2077617320617070726f7665642062757420636f6e7461696e656420616e206572726f7220746861742070726576656e7465640a7375636365737366756c20657865637574696f6e206f6e204d6f6f6e6265616d2e205468697320697373756520686173206265656e20636f7272656374656420696e20746869730a72657375626d697373696f6e2e20496620746869732070726f706f73616c207061737365732c2074686520636f6d6d756e6974792063616e2065787065637420746f206861766520726577617264730a656e61626c656420666f722074686520536166657479204d6f64756c65206f6e2042617365206f6e2054687572736461792e0a0a23232053756d6d6172790a0a546869732070726f706f73616c2061696d7320746f2061637469766174652072657761726420656d697373696f6e7320666f7220746865206e657720536166657479204d6f64756c65206f6e0a426173652c20696e63656e746976697a696e6720757365727320746f2068656c702073656375726520746865204d6f6f6e77656c6c2070726f746f636f6c207468726f756768207374616b696e670a616e6420706172746963697061746520696e206f6e636861696e20676f7665726e616e63652e0a0a2323204f766572766965770a0a546865204d6f6f6e77656c6c20636f6d6d756e6974792068617320726563656e746c7920617070726f7665642074686520696d706c656d656e746174696f6e206f662061206e65770a6d756c7469636861696e20676f7665726e6f7220636f6e747261637420746f20676f7665726e20746865204d6f6f6e77656c6c2070726f746f636f6c2e204164646974696f6e616c6c792c20610a6e65772042617365206e61746976652057454c4c20746f6b656e207574696c697a696e67207468652078455243323020746f6b656e207374616e6461726420686173206265656e20617070726f7665640a666f722075736167652c2077686963682069732061207369676e69666963616e74206d696c6573746f6e6520666f722074686520636f6d6d756e6974792e2042792061646f7074696e6720746869730a6e65772042617365206e61746976652057454c4c20746f6b656e2c20746f6b656e686f6c646572732077696c6c20736f6f6e2062652061626c6520746f207374616b652074686569722057454c4c0a6469726563746c79206f6e204261736520616e6420766f746520696e206f6e636861696e20676f7665726e616e63652e2041206e657720536166657479204d6f64756c652068617320616c72656164790a6265656e206465706c6f796564206f6e204261736520616e64206973207265676973746572656420696e20746865204d756c7469636861696e20566f746520436f6c6c656374696f6e0a636f6e7472616374206173206120736f75726365206f6620766f74696e6720706f7765722c20616c6c6f77696e67207573657273207365637572696e67207468652070726f746f636f6c20746f0a706172746963697061746520696e20676f7665726e616e63652e20496e697469616c6c792c207265776172647320776572652073657420746f2030206f6e20746865206e6577205361666574790a4d6f64756c65206f6e20426173652e20546869732070726f706f73616c2061696d7320746f20656e61626c65207265776172647320666f7220757365727320696e20746865205361666574790a4d6f64756c65207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e0a0a232320496d706c656d656e746174696f6e0a0a546869732070726f706f73616c2077696c6c2073657420616e642066756e64207265776172647320746861742077696c6c20626520646973747269627574656420746f20616c6c205361666574790a4d6f64756c65207374616b657273206f6e20426173652e20496e697469616c20726577617264207370656564732077696c6c2062652073657420746f207468652076616c75650a7265636f6d6d656e64656420627920656d697373696f6e732061646d696e2057617264656e2046696e616e6365206f6620302e383936323735353131363438393631303030302057454c4c207065720a7365636f6e642e202a2a566f74696e672a2a0a0a4120225961792220766f746520696e6469636174657320796f757220737570706f727420666f7220656e61626c696e672072657761726420656d697373696f6e7320666f7220746865205361666574790a4d6f64756c65206f6e20426173652c206173206f75746c696e656420696e20746869732070726f706f73616c2e204120224e61792220766f746520696e6469636174657320796f75720a6f70706f736974696f6e20746f20656e61626c696e672072657761726420656d697373696f6e7320666f722074686520536166657479204d6f64756c65206f6e20426173652e0a0a232320436f6e636c7573696f6e0a0a416464696e67207265776172647320746f2074686520536166657479204d6f64756c65206f6e2042617365206372656174657320696e63656e746976657320666f7220757365727320746f0a6261636b73746f70207468652070726f746f636f6c207769746820746865206e65772042617365206e61746976652057454c4c20746f6b656e2e205374616b696e672057454c4c20696e207468650a536166657479204d6f64756c65206e6f74206f6e6c7920676976657320636f6d6d756e697479206d656d6265727320746865206162696c69747920746f206561726e206e6174697665207969656c640a6f6e20746865697220686f6c64696e67732c2062757420616c736f2070726573656e747320616e20656173792077617920746f2067657420696e766f6c76656420696e20676f7665726e616e63650a61732057454c4c206973206175746f6d61746963616c6c792073656c662064656c6567617465642e0a0000000000000000000000000000000000
```

2024-04-09 22:39 UTC, anajuliabit approved these changes
LGTM

2024-04-12 06:08 UTC, merged