Moonbeam Moonriver Calldata Rewards Simulation
moonwell-fi/moonwell-contracts-v2 pull request #172
Opened 2024-04-11 05:00 UTC by ElliotFriedman

2024-04-11 11:58 UTC, anajuliabit requested changes

2024-04-11 11:58 UTC, anajuliabit commented on test/integration/CalldataExecute.t.sol
> +        vm.prank(0x6972f25AB3FC425EaF719721f0EBD1Cdb58eE451);
could you add this address to a variable so we can know what address is this and why you are pranking?

2024-04-11 11:58 UTC, anajuliabit commented on test/integration/CalldataExecute.t.sol
> +        (bool success, bytes memory err) = address(governorAddress).call(
I don't mind calling it err, but I personally prefer calling it result since it provides us the proposalId.

2024-04-11 11:58 UTC, anajuliabit commented on test/integration/CalldataExecute.t.sol
> +        ERC20Votes(governanceToken).balanceOf(governorAddress);
why this is needed?

2024-04-11 11:58 UTC, anajuliabit commented on test/integration/CalldataExecute.t.sol
> -            .executeProposal(execData);
= We should consider testing a proposal calldata that includes actions on the base. We can then mock the VAA, similar to how we did for the hybrid proposal, and check that the proposal passes on base.

2024-04-11 13:02 UTC, prateek105 commented on test/integration/CalldataExecute.t.sol
> +        address stellaSwapRewarder = addresses.getAddress(
This can removed as it is not used anywhere

2024-04-11 13:08 UTC, prateek105 commented on test/integration/CalldataExecute.t.sol
> +        require(success, "propose failed");
I think this check can be moved up and decode `proposalId` only if call is successful

2024-04-11 23:21 UTC, anajuliabit submitted a review, later dismissed

2024-04-12 03:58 UTC, prateek105 submitted a review, later dismissed

2024-04-12 13:06 UTC, anajuliabit submitted a review, later dismissed

2024-04-12 14:53 UTC, prateek105 submitted a review, later dismissed
lgtm

2024-04-15 11:40 UTC, anajuliabit approved these changes

2024-04-16 07:27 UTC, prateek105 commented on utils/Addresses.json
> +        "name": "CURLY"
I think this address is not used in test and can be removed

2024-04-16 07:29 UTC, prateek105 commented on utils/Addresses.json
> +        "name": "STELLASWAP_REWARDER"
Same, not used in test and can be removed

2024-04-18 12:16 UTC, prateek105 commented
These tests are failing: `testSimExecPassedProposalMoonbeam`, `testSimExistingProposalMoonbeam` and `testSimulateExecMoonriver`. 
What is the idea behind adding these tests that are failing with the current state of contracts on chain.

2024-04-26 06:40 UTC, merged